<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbInsert" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://TargetNamespace.com/syncconsume" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/TEST_APPLICATION/syncCounsumeProject/syncconsume"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/TEST_APPLICATION/syncCounsumeProject/dbInsert">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/syncconsume.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Root" namespace="http://TargetNamespace.com/syncconsume"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/dbInsert.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EmpChetanCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbInsert"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON AUG 21 19:10:44 IST 2023].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:EmpChetanCollection>
         <xsl:for-each select="/ns0:Root/ns0:Element">
            <tns:EmpChetan>
               <tns:empId>
                  <xsl:value-of select="ns0:emp_id"/>
               </tns:empId>
               <tns:firstName>
                  <xsl:value-of select="ns0:emp_name"/>
               </tns:firstName>
               <tns:empCity>
                  <xsl:value-of select="ns0:emp_city"/>
               </tns:empCity>
               <tns:empAge>
                  <xsl:value-of select="ns0:emp_age"/>
               </tns:empAge>
               <tns:lastName1>
                  <xsl:value-of select="ns0:emp_lastname"/>
               </tns:lastName1>
            </tns:EmpChetan>
         </xsl:for-each>
      </tns:EmpChetanCollection>
   </xsl:template>
</xsl:stylesheet>
